import type { Metadata } from "next";
import { Geist } from 'next/font/google'

import "@/styles/global.scss";

import { Sidebar } from "@/components/ui";

const geist = Geist({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
