import '@/styles/global.scss';

import localFont from 'next/font/local';
import type { Metadata } from 'next';

const RIDIFont = localFont({ src: '../public/fonts/RIDIBatang.otf' });
const JetbrainsMono = localFont({
	src: '../public/fonts/JetBrainsMono-Medium.ttf',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko" data-arp="true">
			<body className={`${RIDIFont.className} ${JetbrainsMono.className}`}>
				{children}
			</body>
		</html>
	);
}
