import type {Metadata} from "next";
import "@/styles/global.scss";
import SmoothScroll from "@/components/SmoothScroll/SmoothScroll";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body>
		<SmoothScroll>
			{children}
		</SmoothScroll>
		</body>
		</html>
	);
}
